theme: jekyll-theme-minimal
title: 糸井 友貴
birth_date: "1996-01-01"  # 生年月日（正確な日付に変更してください）
lang: ja
encoding: UTF-8
description: スキルシート・職務経歴書

# サイドバーの設定
show_downloads: false  # ダウンロードボタンを非表示
logo: /images/profile.jpeg  # プロフィール画像
